version: '3.4'
services:
  elasticsearch-kibana:
    container_name: elasticsearch-kibana       # 指定容器的名称
    image: docker.io/kibana:7.11.2                                 # 指定镜像和版本
    restart: always  # 自动重启
    hostname: elasticsearch-kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch-server:9200"
    privileged: true
    volumes: # 挂载目录
      - ./kibana-conf/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      botpy:
        ipv4_address: 172.18.0.36
networks:
  botpy:
    external: true
